# Site settings
title: "Fast Data News"
description: "An amateur news aggregate web site about fast data and stream processing."
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "http://fastdatanews.com" # default is empty
author: "Basri Kahveci"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics: UA-485423-7
disqus_shortname: fast-data-news
